# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(778, 625)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(778, 625))
        MainWindow.setMaximumSize(QtCore.QSize(778, 625))
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Desktop/key.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 741, 553))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_table_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_table_0.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Goudy Stout")
        font.setPointSize(16)
        self.label_table_0.setFont(font)
        self.label_table_0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_table_0.setAlignment(QtCore.Qt.AlignCenter)
        self.label_table_0.setObjectName("label_table_0")
        self.horizontalLayout.addWidget(self.label_table_0)
        self.label_table_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_table_1.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Goudy Stout")
        font.setPointSize(16)
        self.label_table_1.setFont(font)
        self.label_table_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_table_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_table_1.setObjectName("label_table_1")
        self.horizontalLayout.addWidget(self.label_table_1)
        self.label_table_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_table_2.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Goudy Stout")
        font.setPointSize(16)
        self.label_table_2.setFont(font)
        self.label_table_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_table_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_table_2.setObjectName("label_table_2")
        self.horizontalLayout.addWidget(self.label_table_2)
        self.label_table_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_table_3.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Goudy Stout")
        font.setPointSize(16)
        self.label_table_3.setFont(font)
        self.label_table_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_table_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_table_3.setObjectName("label_table_3")
        self.horizontalLayout.addWidget(self.label_table_3)
        self.label_table_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_table_4.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Goudy Stout")
        font.setPointSize(16)
        self.label_table_4.setFont(font)
        self.label_table_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_table_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_table_4.setObjectName("label_table_4")
        self.horizontalLayout.addWidget(self.label_table_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_table_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_table_5.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Goudy Stout")
        font.setPointSize(16)
        self.label_table_5.setFont(font)
        self.label_table_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_table_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_table_5.setObjectName("label_table_5")
        self.horizontalLayout_2.addWidget(self.label_table_5)
        self.label_table_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_table_6.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Goudy Stout")
        font.setPointSize(16)
        self.label_table_6.setFont(font)
        self.label_table_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_table_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_table_6.setObjectName("label_table_6")
        self.horizontalLayout_2.addWidget(self.label_table_6)
        self.label_table_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_table_7.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Goudy Stout")
        font.setPointSize(16)
        self.label_table_7.setFont(font)
        self.label_table_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_table_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_table_7.setObjectName("label_table_7")
        self.horizontalLayout_2.addWidget(self.label_table_7)
        self.label_table_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_table_8.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Goudy Stout")
        font.setPointSize(16)
        self.label_table_8.setFont(font)
        self.label_table_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_table_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_table_8.setObjectName("label_table_8")
        self.horizontalLayout_2.addWidget(self.label_table_8)
        self.label_table_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_table_9.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Goudy Stout")
        font.setPointSize(16)
        self.label_table_9.setFont(font)
        self.label_table_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_table_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_table_9.setObjectName("label_table_9")
        self.horizontalLayout_2.addWidget(self.label_table_9)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_table_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_table_10.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Goudy Stout")
        font.setPointSize(16)
        self.label_table_10.setFont(font)
        self.label_table_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_table_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_table_10.setObjectName("label_table_10")
        self.horizontalLayout_3.addWidget(self.label_table_10)
        self.label_table_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_table_11.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Goudy Stout")
        font.setPointSize(16)
        self.label_table_11.setFont(font)
        self.label_table_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_table_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_table_11.setObjectName("label_table_11")
        self.horizontalLayout_3.addWidget(self.label_table_11)
        self.label_table_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_table_12.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Goudy Stout")
        font.setPointSize(16)
        self.label_table_12.setFont(font)
        self.label_table_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_table_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_table_12.setObjectName("label_table_12")
        self.horizontalLayout_3.addWidget(self.label_table_12)
        self.label_table_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_table_13.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Goudy Stout")
        font.setPointSize(16)
        self.label_table_13.setFont(font)
        self.label_table_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_table_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_table_13.setObjectName("label_table_13")
        self.horizontalLayout_3.addWidget(self.label_table_13)
        self.label_table_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_table_14.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Goudy Stout")
        font.setPointSize(16)
        self.label_table_14.setFont(font)
        self.label_table_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_table_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_table_14.setObjectName("label_table_14")
        self.horizontalLayout_3.addWidget(self.label_table_14)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_table_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_table_15.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Goudy Stout")
        font.setPointSize(16)
        self.label_table_15.setFont(font)
        self.label_table_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_table_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_table_15.setObjectName("label_table_15")
        self.horizontalLayout_4.addWidget(self.label_table_15)
        self.label_table_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_table_16.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Goudy Stout")
        font.setPointSize(16)
        self.label_table_16.setFont(font)
        self.label_table_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_table_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_table_16.setObjectName("label_table_16")
        self.horizontalLayout_4.addWidget(self.label_table_16)
        self.label_table_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_table_17.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Goudy Stout")
        font.setPointSize(16)
        self.label_table_17.setFont(font)
        self.label_table_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_table_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_table_17.setObjectName("label_table_17")
        self.horizontalLayout_4.addWidget(self.label_table_17)
        self.label_table_18 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_table_18.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Goudy Stout")
        font.setPointSize(16)
        self.label_table_18.setFont(font)
        self.label_table_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_table_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_table_18.setObjectName("label_table_18")
        self.horizontalLayout_4.addWidget(self.label_table_18)
        self.label_table_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_table_19.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Goudy Stout")
        font.setPointSize(16)
        self.label_table_19.setFont(font)
        self.label_table_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_table_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_table_19.setObjectName("label_table_19")
        self.horizontalLayout_4.addWidget(self.label_table_19)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_table_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_table_20.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Goudy Stout")
        font.setPointSize(16)
        self.label_table_20.setFont(font)
        self.label_table_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_table_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_table_20.setObjectName("label_table_20")
        self.horizontalLayout_5.addWidget(self.label_table_20)
        self.label_table_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_table_21.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Goudy Stout")
        font.setPointSize(16)
        self.label_table_21.setFont(font)
        self.label_table_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_table_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_table_21.setObjectName("label_table_21")
        self.horizontalLayout_5.addWidget(self.label_table_21)
        self.label_table_22 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_table_22.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Goudy Stout")
        font.setPointSize(16)
        self.label_table_22.setFont(font)
        self.label_table_22.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_table_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_table_22.setObjectName("label_table_22")
        self.horizontalLayout_5.addWidget(self.label_table_22)
        self.label_table_23 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_table_23.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Goudy Stout")
        font.setPointSize(16)
        self.label_table_23.setFont(font)
        self.label_table_23.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_table_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_table_23.setObjectName("label_table_23")
        self.horizontalLayout_5.addWidget(self.label_table_23)
        self.label_table_24 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_table_24.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Goudy Stout")
        font.setPointSize(16)
        self.label_table_24.setFont(font)
        self.label_table_24.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_table_24.setScaledContents(False)
        self.label_table_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_table_24.setObjectName("label_table_24")
        self.horizontalLayout_5.addWidget(self.label_table_24)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout, 4, 1, 1, 3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(140, -1, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_encrypt = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_encrypt.setFont(font)
        self.radioButton_encrypt.setChecked(True)
        self.radioButton_encrypt.setObjectName("radioButton_encrypt")
        self.verticalLayout_2.addWidget(self.radioButton_encrypt)
        self.radioButton_decrypt = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_decrypt.setFont(font)
        self.radioButton_decrypt.setObjectName("radioButton_decrypt")
        self.verticalLayout_2.addWidget(self.radioButton_decrypt)
        self.gridLayout.addLayout(self.verticalLayout_2, 7, 1, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 8, 1, 1, 2)
        self.textEdit_Key = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.textEdit_Key.setFont(font)
        self.textEdit_Key.setObjectName("textEdit_Key")
        self.gridLayout.addWidget(self.textEdit_Key, 5, 1, 1, 3)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 6, 1, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 778, 25))
        self.menubar.setObjectName("menubar")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setTitle("")
        self.menuSetting.setObjectName("menuSetting")
        self.menuSetting_2 = QtWidgets.QMenu(self.menubar)
        self.menuSetting_2.setObjectName("menuSetting_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionFake_Letter = QtWidgets.QAction(MainWindow)
        self.actionFake_Letter.setObjectName("actionFake_Letter")
        self.menuSetting_2.addAction(self.actionFake_Letter)
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuSetting_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.radioButton_encrypt, self.radioButton_decrypt)
        MainWindow.setTabOrder(self.radioButton_decrypt, self.pushButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Playfair GUI"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0000ff;\">TABLE</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Key"))
        self.label_2.setText(_translate("MainWindow", "Text"))
        self.label_table_0.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\">X</span></p></body></html>"))
        self.label_table_1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\">X</span></p></body></html>"))
        self.label_table_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\">X</span></p></body></html>"))
        self.label_table_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\">X</span></p></body></html>"))
        self.label_table_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\">X</span></p></body></html>"))
        self.label_table_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\">X</span></p></body></html>"))
        self.label_table_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\">X</span></p></body></html>"))
        self.label_table_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\">X</span></p></body></html>"))
        self.label_table_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\">X</span></p></body></html>"))
        self.label_table_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\">X</span></p></body></html>"))
        self.label_table_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\">X</span></p></body></html>"))
        self.label_table_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\">X</span></p></body></html>"))
        self.label_table_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\">X</span></p></body></html>"))
        self.label_table_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\">X</span></p></body></html>"))
        self.label_table_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\">X</span></p></body></html>"))
        self.label_table_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\">X</span></p></body></html>"))
        self.label_table_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\">X</span></p></body></html>"))
        self.label_table_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\">X</span></p></body></html>"))
        self.label_table_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\">X</span></p></body></html>"))
        self.label_table_19.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\">X</span></p></body></html>"))
        self.label_table_20.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\">X</span></p></body></html>"))
        self.label_table_21.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\">X</span></p></body></html>"))
        self.label_table_22.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\">X</span></p></body></html>"))
        self.label_table_23.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\">X</span></p></body></html>"))
        self.label_table_24.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\">X</span></p></body></html>"))
        self.radioButton_encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.radioButton_decrypt.setText(_translate("MainWindow", "Decrypt"))
        self.pushButton.setText(_translate("MainWindow", "RUN"))
        self.menuSetting_2.setTitle(_translate("MainWindow", "Setting"))
        self.actionFake_Letter.setText(_translate("MainWindow", "Fake Letter"))

